# Generated by Django 4.2.4 on 2023-09-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_application',
            name='id',
        ),
        migrations.AddField(
            model_name='course_application',
            name='application_id',
            field=models.CharField(default='0000000', max_length=7, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course_application',
            name='english_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
