# Generated by Django 4.2.4 on 2023-09-22 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=254)),
                ('gender', models.CharField(default='', max_length=10)),
                ('date_of_birth', models.DateField(default='')),
                ('citizenship', models.CharField(default='', max_length=255)),
                ('country', models.CharField(default='', max_length=100)),
                ('province', models.CharField(default='', max_length=100)),
                ('street_address1', models.CharField(default='', max_length=255)),
                ('street_address2', models.CharField(blank=True, default='', max_length=255)),
                ('postal_code', models.CharField(default='', max_length=20)),
                ('contact_number', models.CharField(default='', max_length=20)),
                ('qualification1', models.CharField(default='', max_length=255)),
                ('institute1', models.CharField(default='', max_length=255)),
                ('percentage1', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('passing_year1', models.IntegerField(default=0)),
                ('english_proficiency_test', models.CharField(default='', max_length=10)),
                ('english_score', models.DecimalField(decimal_places=2, default='', max_digits=4)),
                ('english_validity', models.IntegerField(default=0)),
                ('proficiency_result', models.FileField(null=True, upload_to='proficiency_results/')),
                ('policy_declaration', models.BooleanField(default=True)),
                ('average_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
