# Generated by Django 4.2.4 on 2023-09-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_course_application_delete_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='seat_available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
