# Generated by Django 4.2.4 on 2023-09-24 09:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_course_application_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_application',
            name='application_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
