# Generated by Django 4.2.4 on 2023-09-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_application_deadline_course_appdeadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbnails/'),
        ),
    ]
