# Generated by Django 4.2.4 on 2023-09-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_course_rejection_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='seat_available',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
