# Generated by Django 4.2.4 on 2023-09-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_course_thumbnail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='region'),
        ),
    ]
