# Generated by Django 4.2.4 on 2023-09-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_course_application_average_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_application',
            name='average_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
