# Generated by Django 4.2.4 on 2023-09-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_course_application_average_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_application',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
