# Generated by Django 4.2.4 on 2023-09-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_course_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_application',
            name='status',
            field=models.CharField(choices=[('applied', 'applied'), ('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='applied', max_length=10),
        ),
    ]
