# Generated by Django 4.2.4 on 2023-09-29 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_course_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='img',
        ),
    ]
