# Generated by Django 4.2.4 on 2023-09-29 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_customuser_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='institute_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_landlord',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='landlord_uid',
        ),
    ]
