# Generated by Django 4.2.4 on 2023-10-02 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_migrant_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrant',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photos/default_profile.png', null=True, upload_to='profile_photos/', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='migrant',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
