# Generated by Django 4.2.4 on 2023-10-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_migrant_profile_photo_alter_migrant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='migrant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course_application',
            name='status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='img',
            field=models.ImageField(default='https://img.freepik.com/free-icon/man_318-677829.jpg', null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='institute_type',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='institute_type'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_landlord',
            field=models.BooleanField(default=False, null=True, verbose_name='is_landlord'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='landlord_uid',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='landlord_uid'),
        ),
        migrations.DeleteModel(
            name='Institute',
        ),
        migrations.DeleteModel(
            name='Migrant',
        ),
    ]
