# Generated by Django 4.2.4 on 2023-10-02 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_migrant_user_remove_course_application_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='img',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='institute_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_landlord',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='landlord_uid',
        ),
        migrations.CreateModel(
            name='Migrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('street_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street Address')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('pincode', models.CharField(blank=True, max_length=10, null=True, verbose_name='Pincode')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='Contact Number')),
                ('profile_photo', models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='profile_photos/', verbose_name='Profile Photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
