# Generated by Django 4.2.4 on 2023-10-05 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_application',
            old_name='application_status',
            new_name='status',
        ),
    ]
