# Generated by Django 4.2.4 on 2023-10-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_course_application_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_application',
            name='application_status',
            field=models.CharField(choices=[('applied', 'Applied'), ('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='applied', max_length=10),
        ),
    ]
